swagger: '2.0'
info:
  title: Sample GKE API
  description: Sample API project on GKE
  version: v1.0.0
host: api.endpoints.sample-gke-api.cloud.goog
schemes:
  - http
  - https
paths:
  /:
    get:
      summary: Health Check
      operationId: healthCheck
      description: Used to determine if API is healthy
      responses:
        200:
          description: ok
  /hello:
    get:
      summary: Hello World
      operationId: sayHello
      description: Returns a greeting to given name, or world
      parameters:
        - name: name
          in: query
          description: The name to greet
          required: false
          type: string
      responses:
        200:
          description: Returns a 200 with greeting.